--- 
title: "A Minimal Book Example"
author: "Yihui Xie (Workshop material by Nils Holmberg)"
date: "`r Sys.time()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Workshop 211021

## workshop material 

in order to follow along, please download github repo as zip [https://github.com/nils-holmberg/sfac-r](https://github.com/nils-holmberg/sfac-r)

demo will be held using [https://rstudio.cloud](https://rstudio.cloud)

## install libs

```{r, eval=F}
install.packages("rmarkdown")
install.packages("bookdown")
#library(rmarkdown)
#library(bookdown)
```

## test compile rmarkdown

cd to sfac-r-main/web/bkd

```{r, eval=F}
#setwd("/cloud/project/sfac-r-main/web/bkd")
rmarkdown::render('document1.Rmd', output_format='all', output_dir='./')
```

## get bookdown demo

download from github [https://github.com/rstudio/bookdown-demo](https://github.com/rstudio/bookdown-demo)

or web/bkd dir

## test compile with bookdown

```{r, eval=F}
bookdown::render_book('index.Rmd', output_dir='./')
```


```{r, eval=F}
```


```{r, eval=F}
```


```{r, eval=F}
```







