---
title: "Online survey"
author: "Nils Holmberg"
date: "210415"
---
<br/>

## Measurements
Complete the Rosenberg Self-Esteem Scale [https://openpsychometrics.org/tests/RSE.php](https://openpsychometrics.org/tests/RSE.php), and take note of all variables being recorded. Discuss in groups and decide which function each variable should have: dependent variable, independent variable, and control variable.

## Operationalization
Think of three operational definitions for self-esteem. Consider the possibility of self-report, behavioural, and physiological measures. Be as precise as you can. Decide which level of measurement is being used for each operationalization. Use the info on this [web page](https://opentextbc.ca/researchmethods/chapter/understanding-psychological-measurement/) for reference.

## Reliability
Continue to discuss the reliability of the variables you noted in the Rosenberg Self-Esteem Scale test using this [web page](https://opentextbc.ca/researchmethods/chapter/reliability-and-validity-of-measurement/). Reliability is consistency across time (test-retest reliability), across items (internal consistency), and across researchers (interrater reliability). 

## Validity
Validity is a judgment based on various types of evidence. The relevant evidence includes whether it covers the construct of interest, and whether the scores it produces are correlated with other variables they are expected to be correlated with and not correlated with variables that are conceptually distinct. Discuss the validity of the variables in the self-esteem test.




