---
title: "SPSS AMOS"
author: "Nils Holmberg"
date: "210401"
---
<br/><br/>

## Introduction

This example dataset introduces readers to Structural Equation Modelling (SEM). This method allows the researcher to test causal relationships between latent factors. It is similar to multiple linear regression and path analysis but is built on the foundation of a reflective measurement model and thus naturally controls for measurement error. SEM follows a two-step process with confirmatory factor analysis (CFA) preceding testing of causal predictions. The current guide takes this perspective. Indeed, a researcher competent in CFA may find SEM somewhat of an anticlimax since the majority of the theoretical and practical mastery required occurs in the former rather than the latter.

The example presented here provides a foundation in SEM. As such, issues pertaining to its specification, assumptions, and interpretation are given. Since this is an introductory dataset, the reader will not be burdened with difficult mathematical notation, nor will advanced issues such as moderation and mediation or growth-curve models be included.

We illustrate the SEM using a subset of data from the International Sponsorship Study (ISS 2016), which broadly captures consumer attitudes towards international sponsorship deals. Specifically, we test the predictive relationships between four latent factors. We test whether animosity towards Germany and ethnocentrism more generally, predict consumer attitudes (ATT) towards German automotive brand SMART. We also investigate whether higher levels of ATT significantly improve perceptions of fit for a hypothetical sponsorship between SMART and the England international soccer team.



